import { getById } from 'e2e/helpers'

export const addressOneField = getById('formField-AddressLineOne')
export const addressTwoField = getById('formField-AddressLineTwo')
export const calendarRightArrow = getById('calendar.header.rightArrow')
export const cityField = getById('formField-City')
export const countryField = getById('formField-Country')
export const dateOfBirthField = getById('formField-DateofBirth')
export const emailField = getById('formField-Email')
export const formPicker = getById('formPicker')
export const memberFullName = getById('memberList-fullName')
export const nameField = getById('formField-Name')
export const postCodeField = getById('formField-Postcode')
export const saveMemberBtn = getById('saveMemberBtn')
export const startDateField = getById('formField-StartDate')
export const startDayField = getById('formField-StartDay')
export const startTimeField = getById('formField-StartTime')
export const surnameField = getById('formField-Surname')
