name: Detox Android Tests

on:
  pull_request:

jobs:
  detox-android:
    name: Run Detox Tests on Android
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up Java
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile 
          yarn global add detox-cli

      # - name: Add Android SDK to PATH
      #   run: |
      #     echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/35.0.0" >> $GITHUB_PATH

      # - name: Install Android SDK
      #   run: |
      #     yes Y | sdkmanager --licenses
      #     sdkmanager --install 'build-tools;35.0.0' platform-tools 'platforms;android-31' 'system-images;android-31;google_apis;x86_64'

      # - name: Build emulator
      #   run: |
      #     echo "no" | avdmanager --verbose create avd --force -n Pixel_XL_API_31 --abi "google_apis/x86_64" -k "system-images;android-31;google_apis;x86_64" --device "pixel_xl"

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          emulator-options: '-no-audio -no-snapshot -no-window'
          profile: pixel_xl
          target: google_apis
          script: ./gradlew connectedCheck

      - name: Start Metro Bundler
        run: yarn metro &

      - name: Build Detox Android APK
        run: yarn detox:build:android

      - name: Run Detox Tests
        run: yarn detox:test:android
