name: Detox Android Tests (2nd approach)

on:
  pull_request:

jobs:
  detox-android:
    runs-on: macos-latest

    env:
      API_LEVEL: 31
      ARCH: arm64-v8a

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: 'temurin'
          java-version: '17'

      - name: Set up environment variables
        run: |
          echo "ANDROID_SDK_ROOT=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV
          echo "PATH=${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/emulator:$PATH" >> $GITHUB_ENV

      - name: Install Command-line Tools
        run: |
          mkdir -p ${{ github.workspace }}/android-sdk/cmdline-tools
          curl -sS https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -o commandlinetools.zip
          unzip -q commandlinetools.zip -d ${{ github.workspace }}/android-sdk/cmdline-tools
          mv ${{ github.workspace }}/android-sdk/cmdline-tools/cmdline-tools ${{ github.workspace }}/android-sdk/cmdline-tools/latest

      - name: Accept Licenses and Install SDK Components
        run: |
          yes | sdkmanager --licenses > /dev/null
          sdkmanager --install "platform-tools" "emulator" "system-images;android-${{ env.API_LEVEL }};default;x86_64"
          sdkmanager --install "platforms;android-${{ env.API_LEVEL }}" "build-tools;${{ env.API_LEVEL }}.0.0"

      - name: Get device name
        id: device
        run: |
          echo "AVD_NAME=$(node -e \"console.log(require('./.detoxrc').devices.emulator.device.avdName)\")" >> $GITHUB_OUTPUT

      - name: Create AVD
        run: |
          echo "AVD_NAME is: ${{ steps.device.outputs.AVD_NAME }}"
          echo "Creating AVD with name: ${{ steps.device.outputs.AVD_NAME }}"
          # Ensure AVD_NAME is correctly passed to the command
          echo "no" | avdmanager create avd -n "${{ steps.device.outputs.AVD_NAME }}" -k "system-images;android-${{ env.API_LEVEL }};default;x86_64" --device "pixel"

      - name: Start Emulator
        run: |
          echo "Starting Emulator: ${{ steps.device.outputs.AVD_NAME }}"
          nohup emulator -avd ${{ steps.device.outputs.AVD_NAME }} -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect > /dev/null 2>&1 &
          adb wait-for-device
          adb shell input keyevent 82 # Unlock emulator

      - name: Verify Emulator
        run: |
          adb devices
          adb shell getprop sys.boot_completed

      # - name: Start Android Emulator
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: ${{ env.API_LEVEL }}
      #     arch: ${{ env.ARCH }}
      #     avd-name: ${{ steps.device.outputs.AVD_NAME }}
      #     emulator-boot-timeout: 300
      #     script: echo 'Starting...'

      # - name: Create AVD and generate snapshot for caching
      #   if: steps.avd-cache.outputs.cache-hit != 'true'
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: ${{ env.API_LEVEL }}
      #     arch: ${{ env.ARCH }}
      #     disable-animations: false
      #     emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     force-avd-creation: false
      #     script: echo 'Generated AVD snapshot for caching.'

      - name: Start Metro bundler
        run: yarn metro &

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: android/app/build
          key: ${{ runner.os }}-detox-build
          restore-keys: ${{ runner.os }}-detox-build

      - name: Build Detox APK
        run: yarn detox:build:android:release

      - name: Run Detox tests
        run: yarn detox:test:android:release --headless --record-logs failing --record-videos failing

      # - name: Get device name
      #   id: device
      #   run: node -e "console.log('AVD_NAME=' + require('./.detoxrc.js').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT

      # - name: Run Detox tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: ${{ env.API_LEVEL }}
      #     arch: ${{ env.ARCH }}
      #     avd-name: ${{ steps.device.outputs.AVD_NAME }}
      #     emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     script: yarn detox:test:android:release --headless --record-logs failing --record-videos failing

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts
