name: Detox Android Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  detox-android:
    runs-on: macos-latest

    env:
      API_LEVEL: 31
      ARCH: arm64-v8a
      AVD_NAME: Pixel_XL_API_31

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: 'temurin'
          java-version: '17'

      - name: Start Metro bundler
        run: yarn metro &

      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: android/app/build
          key: ${{ runner.os }}-detox-build
          restore-keys: ${{ runner.os }}-detox-build

      - name: Build Detox APK
        run: yarn detox:build:android:release

      - name: Run Detox tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          arch: ${{ env.ARCH }}
          avd-name: ${{ env.AVD_NAME }}
          emulator-options: -camera-back none -gpu off -no-boot-anim -no-snapshot-save -no-window -noaudio
          script: yarn detox:test:android:release --headless --record-logs failing --record-videos failing

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts
