name: Detox iOS Tests

on:
  pull_request:

jobs:
  detox-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Install macOS dependencies
        run: brew tap wix/brew && brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true

      - name: Install CocoaPods
        run: bundle exec pod install --project-directory=ios

      - name: Build Detox APP
        run: yarn detox:build:ios:release

      - name: Run Detox Tests
        run: yarn detox:test:ios:release --headless --record-logs all --take-screenshots failing --record-videos failing

      # - name: Upload artifacts
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: detox-artifacts
      #     path: artifacts
